// <auto-generated />
using GestionObras.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionObras.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230324011015_Personas")]
    partial class Personas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("GestionObras.Api.Models.Personas", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Nombres = "Manuel",
                            Telefono = "829-811-4569"
                        },
                        new
                        {
                            PersonaId = 2,
                            Nombres = "Samuel",
                            Telefono = "829-846-5619"
                        },
                        new
                        {
                            PersonaId = 3,
                            Nombres = "Juan",
                            Telefono = "809-578-1978"
                        },
                        new
                        {
                            PersonaId = 4,
                            Nombres = "Ana",
                            Telefono = "849-678-6719"
                        },
                        new
                        {
                            PersonaId = 5,
                            Nombres = "Josefa",
                            Telefono = "849-789-1290"
                        });
                });

            modelBuilder.Entity("GestionObras.Api.Models.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("GestionObras.Api.Models.TiposTrabajos", b =>
                {
                    b.Property<int>("TipoTrabajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoTrabajoId");

                    b.ToTable("TiposTrabajos");
                });
#pragma warning restore 612, 618
        }
    }
}
